---

- name: Check the system
  raw: uname -a
  register: OS

- name: Ubuntu pre-tasks
  import_tasks: ubuntu.yml
  when: '"Ubuntu" in OS.stdout'

- name: FreeBSD pre-tasks
  import_tasks: freebsd.yml
  when: '"FreeBSD" in OS.stdout'

- import_tasks: facts/main.yml
