#cloud-config

packages:
 - strongswan

write_files:
  - path: /etc/strongswan.conf
    permissions: '0600'
    content: ${strongswan.conf}

  - path: /etc/ipsec.conf
    permissions: '0600'
    content: ${ipsec.conf}

  - path: /etc/ipsec.secrets
    permissions: '0600'
    content: ': ECDSA server.pem'

runcmd:
  # just because of `write_files` runs before `users` we need to change the owner by this workaround
  - bash -c 'chown strongswan:root /etc/ipsec.d/{cacerts/ca,certs/server,private/server}.pem'
  - systemctl restart strongswan
  - systemctl enable strongswan
