---

- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - vars/config.yml

  roles:
    - role: pre
      tags: always
    - role: vpn
      tags:
        - vpn
        - update_users
