---

- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - vars/config.yml

  roles:
    - role: pre
      tags: always
    - role: dns_adblocking
      tags:
        - dns
        - adblock
    - role: ssh_tunneling
      tags: ssh_tunneling
    - role: security
      tags: security
    - role: vpn
      tags: vpn

  post_tasks:
    - block:
      - debug:
          msg:
            - "{{ congrats.common.split('\n') }}"
            - "    {{ congrats.p12_pass }}"
            - "    {% if Store_CAKEY is defined and Store_CAKEY == 'N' %}{% else %}{{ congrats.ca_key_pass }}{% endif %}"
            - "    {% if cloud_deployment is defined %}{{ congrats.ssh_access }}{% endif %}"
        tags: always
